# Init and run local search examples

## imports

In [1]:
# read data
from lclpy.io.tsplib import read_tsplib

# move functions
from lclpy.localsearch.move.tsp_array_swap import TspArraySwap
from lclpy.localsearch.move.array_reverse_order import ArrayReverseOrder
from lclpy.localsearch.move.multi_neighbourhood import MultiNeighbourhood

# evaluation function
from lclpy.evaluation.tsp_evaluation_function import TspEvaluationFunction

# Problem class
from lclpy.problem.array_problem import ArrayProblem

# termination functions
from lclpy.termination.min_temperature_termination_criterion import MinTemperatureTerminationCriterion
from lclpy.termination.max_seconds_termination_criterion import MaxSecondsTerminationCriterion

# simulated annealing
from lclpy.localsearch.simulatedannealing.simulated_annealing import SimulatedAnnealing
from lclpy.localsearch.simulatedannealing.geometric_cooling_function import GeometricCoolingFunction
from lclpy.localsearch.simulatedannealing.cnst_iterations_temp_function import CnstIterationsTempFunction

# steepest descent 
from lclpy.localsearch.steepestdescent.steepest_descent import SteepestDescent

# tabu search
from lclpy.localsearch.tabusearch.sum_diff_state import SumDiffState
from lclpy.localsearch.tabusearch.tabu_search import TabuSearch

# variable neighbourhood search
from lclpy.localsearch.vns.variable_neighbourhood import VariableNeighbourhood

import numpy


## Reading the data

In [2]:
data=numpy.loadtxt('data/distanceMatrix',dtype=int)
solution=numpy.loadtxt('data/solution',dtype=int)

# data = read_tsplib('data/distanceMatrix')
distance_matrix =data
print(distance_matrix)
bestscore=0
for i in range(1,distance_matrix.shape[0]):
    bestscore+=distance_matrix[solution[i-1]-1][solution[i]-1]

size = distance_matrix.shape[0]
print(size)
print(bestscore)

[[   0 4727 1205 ... 1542 2379 3744]
 [4727    0 3588 ... 5461 4390 2088]
 [1205 3588    0 ... 2023 1867 2560]
 ...
 [1542 5461 2023 ...    0 1644 3928]
 [2379 4390 1867 ... 1644    0 2532]
 [3744 2088 2560 ... 3928 2532    0]]
48
33088


## simulated annealing

In [3]:
move_1 = TspArraySwap(size)

evaluation_1 = TspEvaluationFunction(distance_matrix, move_1)

problem_1 = ArrayProblem(evaluation_1, move_1, size)

termination_criterion_1 = MinTemperatureTerminationCriterion()

cooling_func = GeometricCoolingFunction(0.95)
i_for_temp = CnstIterationsTempFunction(1500)

algorithm_1 = SimulatedAnnealing(problem_1, termination_criterion_1,
                               cooling_func, i_for_temp)
results_1 = algorithm_1.run()
print(results_1)

Improvement : 155614
Improvement : 150868
Improvement : 148622
Improvement : 148541
Improvement : 142865
Improvement : 142242
Improvement : 141391
Improvement : 141116
Improvement : 138863
Improvement : 137366
Improvement : 135545
Improvement : 132258
Improvement : 131269
Improvement : 130677
Improvement : 128455
Improvement : 128053
Improvement : 126875
Improvement : 126844
Improvement : 125813
Improvement : 122484
Improvement : 121956
Improvement : 121128
Improvement : 119751
Improvement : 117733
Improvement : 114069
Improvement : 110821
Improvement : 110592
Improvement : 110053
Improvement : 109703
Improvement : 107307
Improvement : 106995
Improvement : 106125
Improvement : 105159
Improvement : 101698
Improvement : 101342
Improvement : 101163
Improvement : 98599
Improvement : 98301
Improvement : 96803
Improvement : 94799
Improvement : 91652
Improvement : 88470
Improvement : 87657
Improvement : 85391
Improvement : 85375
Improvement : 84423
Improvement : 82653
Improvement : 80684
Impr

## steepest descent

In [4]:
move_2 = TspArraySwap(size)

evaluation_2 = TspEvaluationFunction(distance_matrix, move_2)

problem_2 = ArrayProblem(evaluation_2, move_2, size)


algorithm_2 = SteepestDescent(problem_2)
results_2 = algorithm_2.run()
print(results_2)

Improvement : 144534
Improvement : 133355
Improvement : 122221
Improvement : 114063
Improvement : 107057
Improvement : 101473
Improvement : 97358
Improvement : 93408
Improvement : 89738
Improvement : 84540
Improvement : 81263
Improvement : 78610
Improvement : 76262
Improvement : 74039
Improvement : 72299
Improvement : 70573
Improvement : 69219
Improvement : 67873
Improvement : 66795
Improvement : 64025
Improvement : 63368
Improvement : 62820
Improvement : 62309
Improvement : 61851
Improvement : 61533
Improvement : 60406
Improvement : 59515
Improvement : 58833
Improvement : 58445
Improvement : 57988
Improvement : 57721
Improvement : 57433
Improvement : 57088
Improvement : 56836
Improvement : 56727
Improvement : 56641
Improvement : 56578
Improvement : 56212
Improvement : 55996
Improvement : 55737
Improvement : 55690
Improvement : 55658
Results(best_order=array([ 0,  1,  3, 25,  9, 30, 37,  7,  8, 39, 10, 12, 24, 13, 22, 11, 14,
       45, 32, 19, 46, 20, 31, 23, 34, 44, 42, 16, 26, 18, 3

## tabu search

In [5]:
move_3 = TspArraySwap(size)

evaluation_3 = TspEvaluationFunction(distance_matrix, move_3)

problem_3 = ArrayProblem(evaluation_3, move_3, size)

termination_3 = MaxSecondsTerminationCriterion(10)

diff_state_3 = SumDiffState()

algorithm_3 = TabuSearch(problem_3, termination_3, diff_state_3, 11)
results_3 = algorithm_3.run()
print(results_3)

Improvement : 144534
Improvement : 133355
Improvement : 122221
Improvement : 114063
Improvement : 107057
Improvement : 101473
Improvement : 97358
Improvement : 93408
Improvement : 89738
Improvement : 84540
Improvement : 81263
Improvement : 78610
Improvement : 76262
Improvement : 74039
Improvement : 72685
Improvement : 71339
Improvement : 70261
Improvement : 67298
Improvement : 64517
Improvement : 63045
Improvement : 62527
Improvement : 62069
Improvement : 61696
Improvement : 61317
Improvement : 59128
Improvement : 58826
Improvement : 58559
Improvement : 58307
Improvement : 58132
Improvement : 58006
Improvement : 57897
Improvement : 57788
Improvement : 57736
Improvement : 57044
Improvement : 56904
Improvement : 56895
Improvement : 56654
Improvement : 56538
Improvement : 55222
Improvement : 55152
Improvement : 55085
Improvement : 55023
Improvement : 54504
Improvement : 54198
Improvement : 53195
Improvement : 52832
Improvement : 52627
Improvement : 52515
Improvement : 52474
Improvement : 

## variable neighbourhood search

In [6]:
move_a = TspArraySwap(size)
move_b = ArrayReverseOrder(size)

moves = [move_a, move_b]

move_4 = MultiNeighbourhood(moves)

evaluation_4 = TspEvaluationFunction(distance_matrix, move_4)

problem_4 = ArrayProblem(evaluation_4, move_4, size)


algorithm_4 = VariableNeighbourhood(problem_4)
results_4 = algorithm_4.run()
print(results_4)

Improvement : 144534
Improvement : 133355
Improvement : 122221
Improvement : 114063
Improvement : 107057
Improvement : 101473
Improvement : 97358
Improvement : 93408
Improvement : 89738
Improvement : 84540
Improvement : 81263
Improvement : 78610
Improvement : 76262
Improvement : 74039
Improvement : 72299
Improvement : 70573
Improvement : 69219
Improvement : 67873
Improvement : 66795
Improvement : 64025
Improvement : 63368
Improvement : 62820
Improvement : 62309
Improvement : 61851
Improvement : 61533
Improvement : 60406
Improvement : 59515
Improvement : 58833
Improvement : 58445
Improvement : 57988
Improvement : 57721
Improvement : 57433
Improvement : 57088
Improvement : 56836
Improvement : 56727
Improvement : 56641
Improvement : 56578
Improvement : 56212
Improvement : 55996
Improvement : 55737
Improvement : 55690
Improvement : 55658
Improvement : 44961
Improvement : 44411
Improvement : 44301
Improvement : 44283
Improvement : 44180
Improvement : 44169
Improvement : 38873
Improvement : 